### ISSUE TITLE
commitlint deletes long lines

### ISSUE THREAD

**Issue by morremeyer** [morremeyer/charts#174] opened 2022-11-02 16:56 UTC
As pointed out in #173, commitlint deletes the commit message if there's lines over 100 characters. 
That should not happen.

**Comment by ekeih** [comment] 2022-11-02 17:08
I think in general the issue is that the commit message is dropped if the check fails. Maybe there is also some way to tell pre-commit or the linter to store the failed message somewhere like `.commitlint-failed.txt` or just print it to the terminal.
The line length is only one case where it was annoying and felt especially unjustified 😆

**Comment by morremeyer** [comment] 2022-11-05 08:51
commitlint/pre-commit shouldn't drop the message. 

If it has a linting error, the full message as supplied should be printed to the terminal. This has been the case in the past when I encountered it.

Can you verify that this does not happen anymore?

**Comment by ekeih** [comment] 2022-11-12 14:43
Interesting, I am 95% sure that it only printed a part of my commit message to the terminal. But now I can't reproduce it anymore, so maybe I am mistaken.
Let's close this and only revisit it if it happens again. Sorry for the noise.

**Closed as not planned by ekeih** 2022-11-12 14:43 UTC
Labels: bug
